import type { SevereWeatherResponse } from '@sentinel/types'

/**
 * Returns a demo response with realistic HIGH/CRITICAL scenario data.
 * Clearly marked with demo: true.
 */
export function buildDemoResponse(lat: number, lon: number): SevereWeatherResponse {
  const now = new Date()

  return {
    demo: true,
    location: { lat, lon },
    sources: {
      forecast: 'Demo Mode (simulated data)',
      active_alerts: 'Demo Mode (simulated alerts)',
    },
    limitations: [
      'THIS IS DEMO DATA — not real weather information.',
      'This is not an exact tornado prediction.',
      'The index estimates favorable conditions for severe storms using available forecast variables.',
      'Official NWS alerts are mainly available for the United States and territories.',
    ],
    active_alerts: [
      {
        event: 'Tornado Watch',
        severity: 'Severe',
        urgency: 'Expected',
        headline: '[DEMO] Tornado Watch issued for the area until 10:00 PM',
        area_description: 'Demo County, Demo State',
        effective: now.toISOString(),
        expires: new Date(now.getTime() + 6 * 3600000).toISOString(),
        geometry: null,
      },
      {
        event: 'Severe Thunderstorm Warning',
        severity: 'Severe',
        urgency: 'Immediate',
        headline: '[DEMO] Severe Thunderstorm Warning with 70 mph gusts',
        area_description: 'Demo County, Demo State',
        effective: now.toISOString(),
        expires: new Date(now.getTime() + 2 * 3600000).toISOString(),
        geometry: null,
      },
    ],
    forecast_risk: [
      {
        window: 'Now',
        timestamp: now.toISOString(),
        score: 72,
        risk_level: 'HIGH',
        variables: {
          temperature_2m: 31.2,
          relative_humidity_2m: 78,
          surface_pressure: 1003,
          precipitation: 4.5,
          rain: 4.5,
          showers: 0,
          weather_code: 95,
          cloud_cover: 92,
          wind_speed_10m: 38,
          wind_direction_10m: 210,
          wind_gusts_10m: 72,
          wind_speed_80m: 58,
          wind_direction_80m: 250,
          wind_speed_120m: 65,
          wind_direction_120m: 270,
        },
        drivers: [
          'Critical wind gusts (72 km/h)',
          'Wind shear proxy detected (speed diff 27 km/h, direction diff 60°)',
          'High humidity (78%) and temperature (31.2°C) favor convection',
          'Pressure dropping (3.2 hPa in 3h)',
          'Thunderstorm weather code (95)',
        ],
        confidence: 85,
        impact_corridor: {
          direction_label: 'NE',
          bearing_degrees: 30,
          estimated_distance_km_1h: 55,
          estimated_distance_km_3h: 165,
          estimated_distance_km_6h: 330,
          explanation: 'Probable impact corridor follows the dominant low-level wind direction (NE, bearing 30°). Distances estimated from mean wind speed and gust intensity.',
        },
      },
      {
        window: '+1h',
        timestamp: new Date(now.getTime() + 3600000).toISOString(),
        score: 81,
        risk_level: 'CRITICAL',
        variables: {
          temperature_2m: 32.0,
          relative_humidity_2m: 82,
          surface_pressure: 1001,
          precipitation: 8.2,
          rain: 8.2,
          showers: 2.1,
          weather_code: 95,
          cloud_cover: 95,
          wind_speed_10m: 42,
          wind_direction_10m: 215,
          wind_gusts_10m: 85,
          wind_speed_80m: 64,
          wind_direction_80m: 255,
          wind_speed_120m: 72,
          wind_direction_120m: 275,
        },
        drivers: [
          'Critical wind gusts (85 km/h)',
          'Wind shear proxy detected (speed diff 30 km/h, direction diff 60°)',
          'High humidity (82%) and temperature (32°C) favor convection',
          'Rapid pressure drop (5.0 hPa in 3h)',
          'Thunderstorm weather code (95)',
          'Dense cloud cover (95%)',
        ],
        confidence: 85,
        impact_corridor: {
          direction_label: 'NE',
          bearing_degrees: 35,
          estimated_distance_km_1h: 63,
          estimated_distance_km_3h: 190,
          estimated_distance_km_6h: 380,
          explanation: 'Probable impact corridor follows the dominant low-level wind direction (NE, bearing 35°). Distances estimated from mean wind speed and gust intensity.',
        },
      },
      {
        window: '+3h',
        timestamp: new Date(now.getTime() + 3 * 3600000).toISOString(),
        score: 65,
        risk_level: 'HIGH',
        variables: {
          temperature_2m: 29.5,
          relative_humidity_2m: 75,
          surface_pressure: 1004,
          precipitation: 3.1,
          rain: 3.1,
          showers: 0,
          weather_code: 80,
          cloud_cover: 88,
          wind_speed_10m: 32,
          wind_direction_10m: 220,
          wind_gusts_10m: 58,
          wind_speed_80m: 48,
          wind_direction_80m: 250,
          wind_speed_120m: null,
          wind_direction_120m: null,
        },
        drivers: [
          'Strong wind gusts (58 km/h)',
          'Wind shear proxy detected (speed diff 16 km/h, direction diff 30°)',
          'High humidity (75%) and temperature (29.5°C) favor convection',
        ],
        confidence: 70,
        impact_corridor: {
          direction_label: 'NE',
          bearing_degrees: 40,
          estimated_distance_km_1h: 45,
          estimated_distance_km_3h: 135,
          estimated_distance_km_6h: 270,
          explanation: 'Probable impact corridor follows the dominant low-level wind direction (NE, bearing 40°). Distances estimated from mean wind speed and gust intensity.',
        },
      },
      {
        window: '+6h',
        timestamp: new Date(now.getTime() + 6 * 3600000).toISOString(),
        score: 38,
        risk_level: 'MODERATE',
        variables: {
          temperature_2m: 26.8,
          relative_humidity_2m: 68,
          surface_pressure: 1008,
          precipitation: 1.2,
          rain: 1.2,
          showers: 0,
          weather_code: 61,
          cloud_cover: 72,
          wind_speed_10m: 22,
          wind_direction_10m: 230,
          wind_gusts_10m: 38,
          wind_speed_80m: 35,
          wind_direction_80m: 255,
          wind_speed_120m: null,
          wind_direction_120m: null,
        },
        drivers: [
          'Moderate wind gusts (38 km/h)',
          'High humidity (68%) and temperature (26.8°C) favor convection',
        ],
        confidence: 70,
        impact_corridor: {
          direction_label: 'NE',
          bearing_degrees: 50,
          estimated_distance_km_1h: 30,
          estimated_distance_km_3h: 90,
          estimated_distance_km_6h: 180,
          explanation: 'Probable impact corridor follows the dominant low-level wind direction (NE, bearing 50°). Distances estimated from mean wind speed and gust intensity.',
        },
      },
    ],
    mistral_analysis: {
      risk_summary: '[DEMO] Conditions strongly favor severe thunderstorm development with possible tornado-favorable environment. Active Tornado Watch in effect.',
      technical_explanation: '[DEMO] Strong low-level wind shear proxy combined with high CAPE-equivalent surface conditions (high humidity + high temperature) create a favorable environment for rotating updrafts. The SSPI peaks at CRITICAL in the +1h window.',
      citizen_alert_160_chars: '[DEMO] Severe storm risk HIGH. Tornado Watch active. Seek shelter now if skies darken. Stay away from windows.',
      municipal_briefing: '[DEMO] Recommended activation of emergency protocols. Storm system expected to intensify over the next 1-3 hours with possible tornadic activity.',
      recommended_actions: [
        '[DEMO] Activate municipal severe weather sirens',
        '[DEMO] Open public shelters',
        '[DEMO] Alert first responders for possible tornado response',
        '[DEMO] Advise residents to move to interior rooms on lowest floor',
        '[DEMO] Monitor official NWS updates continuously',
      ],
      shelter_guidance: '[DEMO] Move to interior room on lowest floor. Stay away from windows. If in mobile home, evacuate to nearest sturdy structure.',
      uncertainty_note: '[DEMO] This is demo data. In production, AI analysis uses real forecast data. Actual tornado formation depends on mesoscale factors not captured by surface observations alone.',
    },
  }
}
