"use client"

import { useState } from "react"
import { THREAT_COLORS, type ThreatLevel } from "./types"

interface Props {
  threat: ThreatLevel
  aqi: number
}

const ACTIONS: Record<ThreatLevel, string[]> = {
  LOW: [
    "Monitor air quality levels",
    "Normal activities permitted",
    "Keep emergency contacts ready",
  ],
  MODERATE: [
    "Sensitive groups reduce outdoor time",
    "Close windows in affected zones",
    "Avoid strenuous outdoor exercise",
    "Alert healthcare facilities",
  ],
  HIGH: [
    "Suspend outdoor school activities",
    "Deploy N95 masks to vulnerable zones",
    "Avoid outdoor exercise — all groups",
    "Prepare emergency response teams",
    "Alert nearby hospitals",
    "Issue public health advisory",
  ],
  CRITICAL: [
    "IMMEDIATE: Evacuate affected zones",
    "Suspend ALL outdoor activities",
    "Deploy emergency medical units",
    "Activate incident command center",
    "Issue emergency broadcast alert",
    "Request regional air support",
    "Open emergency shelters",
  ],
}

function now(): string {
  return new Date().toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })
}

export function ActionPlan({ threat, aqi }: Props) {
  const color   = THREAT_COLORS[threat]
  const actions = ACTIONS[threat]
  const [open, setOpen] = useState(true)

  return (
    <div
      className="bg-black/80 backdrop-blur-md border rounded-sm p-3 font-mono"
      style={{
        borderColor: `${color}40`,
        animation:   "slideInRight 0.4s ease-out",
      }}
    >
      <button
        onClick={() => setOpen(o => !o)}
        className="flex items-center gap-2 w-full text-left"
      >
        <span
          className="text-[10px] tracking-widest uppercase font-semibold"
          style={{ color }}
        >
          AI RESPONSE PLAN
        </span>
        <div className="flex-1 h-px" style={{ backgroundColor: `${color}30` }} />
        <span className="text-[9px] text-muted-foreground tabular-nums">
          AQI {Math.round(aqi)}
        </span>
        <svg
          width="10" height="10" viewBox="0 0 10 10" fill="none"
          style={{
            transform: open ? "rotate(0deg)" : "rotate(-90deg)",
            transition: "transform 0.2s ease",
            flexShrink: 0,
          }}
        >
          <path d="M2 3.5L5 6.5L8 3.5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/>
        </svg>
      </button>

      {open && (
        <div className="mt-3">
          <div className="flex flex-col gap-2">
            {actions.map((action, i) => (
              <div
                key={i}
                className="flex items-start gap-2"
                style={{ animation: `fadeInUp 0.3s ease-out ${i * 0.05}s both` }}
              >
                <span
                  className="text-[10px] font-bold tabular-nums flex-shrink-0 mt-px"
                  style={{ color }}
                >
                  {String(i + 1).padStart(2, "0")}
                </span>
                <span className="text-[10px] text-foreground/80 leading-tight">{action}</span>
              </div>
            ))}
          </div>

          <div
            className="mt-3 pt-2 border-t"
            style={{ borderColor: `${color}20` }}
          >
            <span className="text-[9px] text-muted-foreground">
              Generated by SENTINEL AI · {now()}
            </span>
          </div>
        </div>
      )}
    </div>
  )
}
